# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
ingress:
  ## If true, Kubernetes Dashboard Ingress will be created.
  # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/rewrite-target:  /
  enabled: true
  paths:
    - /
  #  - /*
  # add these changes to jx-environment for chart
  subdomains:
    - <react-app-template>
app:
  env:
  - name: PORT
    value: "80"
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: <react-app-template>
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
configProp: false
global:
  domain: aa.dsawsnprd.massmutual.com
